# Generated by Django 4.2.23 on 2025-07-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_team_customuser_repots_to_alter_customuser_role_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="repots_to",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="team",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
    ]
