# Generated by Django 4.2.23 on 2025-06-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_category_remove_task_category_task_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.ManyToManyField(blank=True, to="tasks.category"),
        ),
    ]
