# Generated by Django 4.2.23 on 2025-06-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
