# Generated by Django 4.2.23 on 2025-06-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_remove_task_category_delete_category_task_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="task",
            name="category",
        ),
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.ManyToManyField(blank=True, to="tasks.category"),
        ),
    ]
