# Generated by Django 4.2.23 on 2025-06-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_category_user_alter_category_unique_together"),
    ]

    operations = []
