# Generated by Django 4.2.23 on 2025-06-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_auto_20250627_1135"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="task",
            name="reminder_sent_for_1_day",
        ),
        migrations.RemoveField(
            model_name="task",
            name="reminder_sent_for_2_days",
        ),
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.ManyToManyField(blank=True, to="tasks.category"),
        ),
        migrations.RemoveField(
            model_name="category",
            name="user",
        ),
    ]
