# Generated by Django 4.2.23 on 2025-06-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_alter_category_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="tasks.category"
            ),
        ),
    ]
