# Generated by Django 4.2.23 on 2025-06-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_alter_task_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reminder_sent_for_1_day",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="reminder_sent_for_2_days",
            field=models.BooleanField(default=False),
        ),
    ]
