# Generated by Django 4.2.23 on 2025-06-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0012_task_reminder_sent_for_1_day_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="reminder_sent_for_1_day",
        ),
        migrations.RemoveField(
            model_name="task",
            name="reminder_sent_for_2_days",
        ),
    ]
